# Generated by Django 4.0.1 on 2022-01-27 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_movement', '0003_alter_file_movement_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_movement',
            old_name='Location',
            new_name='Project_location',
        ),
    ]
