# Generated by Django 4.0.1 on 2022-01-27 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_movement', '0004_rename_location_file_movement_project_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_movement',
            name='File_number',
        ),
    ]
